# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  mac-permissions: circleci/macos@1.0.0

jobs:
  build-and-test:
    macos:
      xcode: 12.3.0 # Specify the Xcode version to use
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: check
    steps:
      - checkout
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: sudo bundle update --bundler
      - run: brew install swiftlint
      - run: bundle install
      - mac-permissions/add-permission:
          bundle-id: "com.addisonhanrattie.TouchBarVisualizer"
          permission-type: "kTCCServiceMicrophone"
      - mac-permissions/list-permissions
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - run: ls ./build/Build/Products/
      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
workflows:
  build-test:
    jobs:
      - build-and-test
